In [2]:
# EX NO: 3 - Data Cleaning

import pandas as pd

# Load dataset
df = pd.read_csv("indexData.csv")


# ==========================================
# CHECK MISSING VALUES
# ==========================================

print("===== DATASET INFO =====")
df.info()

print("\n===== MISSING VALUES IN EACH COLUMN =====")
print(df.isnull().sum())

print("\n===== TOTAL MISSING VALUES =====")
print(df.isnull().sum().sum())

print("\n===== ANY MISSING VALUES? =====")
print(df.isnull().values.any())

print("\n===== NON-MISSING VALUES COUNT =====")
print(df.notnull().sum())


# ==========================================
# FILL MISSING VALUES
# ==========================================

# Fill all missing values with 0
df_constant = df.fillna(0)

print("\n===== CONSTANT VALUE =====")
display(df_constant.head())


# Fill 'Open' column with mean
df_mean = df.copy()
df_mean["Open"] = df_mean["Open"].fillna(df_mean["Open"].mean())

print("\n===== MEAN =====")
display(df_mean.head())


# Fill 'Close' column with median
df_median = df.copy()
df_median["Close"] = df_median["Close"].fillna(df_median["Close"].median())

print("\n===== MEDIAN =====")
display(df_median.head())


# Fill 'Index' column with mode
df_mode = df.copy()
df_mode["Index"] = df_mode["Index"].fillna(df_mode["Index"].mode()[0])

print("\n===== MODE =====")
display(df_mode.head())


# Forward Fill
df_ffill = df.ffill()

print("\n===== FORWARD FILL =====")
display(df_ffill.head())


# Backward Fill
df_bfill = df.bfill()

print("\n===== BACKWARD FILL =====")
display(df_bfill.head())


# ==========================================
# DROP MISSING VALUES
# ==========================================

# Drop rows with missing values
df_drop_rows = df.dropna()

print("\n===== DROP ROWS =====")
display(df_drop_rows.head())


# Drop columns with missing values
df_drop_cols = df.dropna(axis=1)

print("\n===== DROP COLUMNS =====")
display(df_drop_cols.head())


# Drop rows having any missing value
df_any = df.dropna(how="any")

print("\n===== DROP HOW='ANY' =====")
display(df_any.head())


# Drop rows where all values are missing
df_all = df.dropna(how="all")

print("\n===== DROP HOW='ALL' =====")
display(df_all.head())


# Keep rows with at least 5 non-null values
df_thresh = df.dropna(thresh=5)

print("\n===== THRESH = 5 =====")
display(df_thresh.head())


# Drop rows where 'Open' or 'Close' is missing
df_subset = df.dropna(subset=["Open", "Close"])

print("\n===== SUBSET (Open, Close) =====")
display(df_subset.head())


# Drop missing values permanently
df_copy = df.copy()
df_copy.dropna(inplace=True)

print("\n===== AFTER inplace=True =====")
display(df_copy.head())

===== DATASET INFO =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112457 entries, 0 to 112456
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Index      112457 non-null  object
 1   Date       112457 non-null  object
 2   Open       110253 non-null  float64
 3   High       110253 non-null  float64
 4   Low        110253 non-null  float64
 5   Close      110253 non-null  float64
 6   Adj Close  110253 non-null  float64
 7   Volume     110253 non-null  float64
dtypes: float64(6), object(2)
memory usage: 6.9+ MB

===== MISSING VALUES IN EACH COLUMN =====
Index           0
Date            0
Open         2204
High         2204
Low          2204
Close        2204
Adj Close    2204
Volume       2204
dtype: int64

===== TOTAL MISSING VALUES =====
13224

===== ANY MISSING VALUES? =====
True

===== NON-MISSING VALUES COUNT =====
Index        112457
Date         112457
Open         110253
High         110253
Low          110253
Close        110253
Adj Close    110253
Volume       110253
dtype: int64

===== CONSTANT VALUE =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== MEAN =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== MEDIAN =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== MODE =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== FORWARD FILL =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== BACKWARD FILL =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== DROP ROWS =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== DROP COLUMNS =====

  Index        Date
0   NYA  1965-12-31
1   NYA  1966-01-03
2   NYA  1966-01-04
3   NYA  1966-01-05
4   NYA  1966-01-06

===== DROP HOW='ANY' =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== DROP HOW='ALL' =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== THRESH = 5 =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== SUBSET (Open, Close) =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== AFTER inplace=True =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0