In [2]:
# EDA - Data Import and Export

# Import required libraries
import pandas as pd
import sqlite3


# Load the indexData dataset
df = pd.read_csv("indexData.csv")


# Display the complete dataset
print("===== DATASET =====")
display(df)


# Display first five records
print("\n===== FIRST FIVE ROWS =====")
display(df.head())


# Display last five records
print("\n===== LAST FIVE ROWS =====")
display(df.tail())


# Display dataset information
print("\n===== DATASET INFORMATION =====")
df.info()


# Display statistical summary
print("\n===== STATISTICAL SUMMARY =====")
display(df.describe(include='all'))


# Display dataset shape
print("\nDataset Shape:")
print(df.shape)


# Display column names
print("\nColumns:")
print(df.columns)


# Check missing values
print("\n===== MISSING VALUES =====")
print(df.isnull().sum())


# Export dataset to CSV
df.to_csv("indexData_export.csv", index=False)

print("\nCSV file exported successfully!")


# Export dataset to Excel
df.to_excel("indexData_export.xlsx", index=False)

print("Excel file exported successfully!")


# Create SQLite database
conn = sqlite3.connect("indexData.db")


# Export DataFrame to SQL table
df.to_sql(
    "indexData",
    conn,
    if_exists="replace",
    index=False
)

print("Dataset exported successfully to SQLite database!")


# Close the connection
conn.close()

===== DATASET =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0
...,...,...,...,...,...,...,...,...
112452,N100,2021-05-27,1241.119995,1251.910034,1241.119995,1247.069946,1247.069946,379696400.0
112453,N100,2021-05-28,1249.469971,1259.209961,1249.030029,1256.599976,1256.599976,160773400.0
112454,N100,2021-05-31,1256.079956,1258.880005,1248.140015,1248.930054,1248.930054,91173700.0
112455,N100,2021-06-01,1254.609985,1265.660034,1254.609985,1258.579956,1258.579956,155179900.0
112456,N100,2021-06-02,1258.489990,1263.709961,1258.239990,1263.619995,1263.619995,148465000.0

===== FIRST FIVE ROWS =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
0,NYA,1965-12-31,528.690002,528.690002,528.690002,528.690002,528.690002,0.0
1,NYA,1966-01-03,527.210022,527.210022,527.210022,527.210022,527.210022,0.0
2,NYA,1966-01-04,527.840027,527.840027,527.840027,527.840027,527.840027,0.0
3,NYA,1966-01-05,531.119995,531.119995,531.119995,531.119995,531.119995,0.0
4,NYA,1966-01-06,532.070007,532.070007,532.070007,532.070007,532.070007,0.0

===== LAST FIVE ROWS =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
112452,N100,2021-05-27,1241.119995,1251.910034,1241.119995,1247.069946,1247.069946,379696400.0
112453,N100,2021-05-28,1249.469971,1259.209961,1249.030029,1256.599976,1256.599976,160773400.0
112454,N100,2021-05-31,1256.079956,1258.880005,1248.140015,1248.930054,1248.930054,91173700.0
112455,N100,2021-06-01,1254.609985,1265.660034,1254.609985,1258.579956,1258.579956,155179900.0
112456,N100,2021-06-02,1258.489990,1263.709961,1258.239990,1263.619995,1263.619995,148465000.0

===== DATASET INFORMATION =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112457 entries, 0 to 112456
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Index      112457 non-null  object
 1   Date       112457 non-null  object
 2   Open       110253 non-null  float64
 3   High       110253 non-null  float64
 4   Low        110253 non-null  float64
 5   Close      110253 non-null  float64
 6   Adj Close  110253 non-null  float64
 7   Volume     110253 non-null  float64
dtypes: float64(6), object(2)
memory usage: 6.9+ MB

===== STATISTICAL SUMMARY =====

,Index,Date,Open,High,Low,Close,Adj Close,Volume
count,112457,112457,110253.000000,110253.000000,110253.000000,110253.000000,110253.000000,1.102530e+05
unique,14,14731,NaN,NaN,NaN,NaN,NaN,NaN
top,N225,2017-11-03,NaN,NaN,NaN,NaN,NaN,NaN
freq,14500,14,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,7658.515222,7704.372961,7608.000422,7657.545872,7657.351729,1.273975e+09
std,NaN,NaN,9011.478913,9066.638548,8954.506981,9011.510444,9011.608900,4.315783e+09
min,NaN,NaN,54.869999,54.869999,54.869999,54.869999,54.869999,0.000000e+00
25%,NaN,NaN,1855.030029,1864.510010,1843.979980,1855.060059,1854.179565,0.000000e+00
50%,NaN,NaN,5194.089844,5226.279785,5154.049805,5194.750000,5194.750000,4.329000e+05
75%,NaN,NaN,10134.299810,10207.820310,10060.349610,10134.830080,10134.830080,1.734314e+08
max,NaN,NaN,68775.062500,69403.750000,68516.992190,68775.062500,68775.062500,9.440374e+10

Dataset Shape:
(112457, 8)

Columns:
Index(['Index', 'Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

===== MISSING VALUES =====
Index           0
Date            0
Open         2204
High         2204
Low          2204
Close        2204
Adj Close    2204
Volume       2204
dtype: int64

CSV file exported successfully!
Excel file exported successfully!
Dataset exported successfully to SQLite database!

In [3]:
import pandas as pd

# Load dataset, skipping bad lines to avoid ParserError
df = pd.read_csv(
    "indexData.csv",
    on_bad_lines='skip',
    engine='python'
)

print("===== DATASET INFO =====")
df.info()

print("\n===== MISSING VALUES IN EACH COLUMN =====")
print(df.isnull().sum())

print("\n===== TOTAL MISSING VALUES =====")
print(df.isnull().sum().sum())

print("\n===== ANY MISSING VALUES? =====")
print(df.isnull().values.any())

print("\n===== NON-MISSING VALUES COUNT =====")
print(df.notnull().sum())

===== DATASET INFO =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112457 entries, 0 to 112456
Data columns (total 8 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Index      112457 non-null  object
 1   Date       112457 non-null  object
 2   Open       110253 non-null  float64
 3   High       110253 non-null  float64
 4   Low        110253 non-null  float64
 5   Close      110253 non-null  float64
 6   Adj Close  110253 non-null  float64
 7   Volume     110253 non-null  float64
dtypes: float64(6), object(2)
memory usage: 6.9+ MB

===== MISSING VALUES IN EACH COLUMN =====
Index           0
Date            0
Open         2204
High         2204
Low          2204
Close        2204
Adj Close    2204
Volume       2204
dtype: int64

===== TOTAL MISSING VALUES =====
13224

===== ANY MISSING VALUES? =====
True

===== NON-MISSING VALUES COUNT =====
Index        112457
Date         112457
Open         110253
High         110253
Low          110253
Close        110253
Adj Close    110253
Volume       110253
dtype: int64